[package]
name = "levenshtein-checker"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "spork-checker"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }

[build-dependencies]
clap = { version = "4.5.23", features = ["derive"] }
