[package]
name = "sporky-checker"
version = "1.0.0"
edition = "2021"
description = "Simple levenshtein spell checker app"

[[bin]]
name = "sporky-checker"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
rust-embed = "8.5.0"
